const collegeNames = [
    "Hamilton College",
    "Bates College",
    "Wesleyan University",
    "Princeton University",
    "Colorado College",
    "University Of Pennsylvania",
    "Cornell University",
    "Harvard College",
    "Washington And Lee University",
    "Yale University",
    "Williams College",
    "Swarthmore College",
    "Grinnell College",
    "Carleton College",
    "Brown University",
    "Smith College",
    "Haverford College",
    "Columbia University",
    "Reed College",
    "Washington University In St Louis",
    "Mount Holyoke College",
    "Middlebury College",
    "Dartmouth College",
    "Connecticut College",
    "Bowdoin College",
    "Boston College",
    "Amherst College",
    "Skidmore College",
    "Wellesley College",
    "Vanderbilt University",
    "Northwestern University",
    "Colgate University",
    "Oberlin College",
    "Bryn Mawr College",
    "Emory University",
    "Occidental College",
    "Johns Hopkins University",
    "Colby College",
    "University Of Chicago",
    "Harvey Mudd College",
    "Pomona College",
    "Davidson College",
    "California Institute Of Technology",
    "St Olaf College",
    "Duke University",
    "Brandeis University",
    "University Of Notre Dame",
    "College Of The Holy Cross",
    "Georgetown University",
    "Wake Forest University",
    "Pitzer College",
    "University Of Rochester",
    "Scripps College",
    "Stanford University",
    "University Of Dayton",
    "Loyola University Maryland",
    "Dickinson College",
    "University Of Southern California",
    "Babson College",
    "Case Western Reserve University",
    "Wabash College",
    "Lehigh University",
    "Rochester Institute Of Technology",
    "Lafayette College",
    "University Of Miami",
    "Macalester College",
    "Rice University",
    "Cooper Union For The Advancement Of Science And Art",
    "Rhodes College",
    "Stonehill College",
    "Lawrence University",
    "Valparaiso University",
    "College Of Wooster",
    "College Of The Ozarks",
    "Bryant University",
    "Worcester Polytechnic Institute",
    "Cedarville University",
    "Spelman College",
    "Syracuse University",
    "Hendrix College",
    "Luther College",
    "Mercer University",
    "George Washington University",
    "Gustavus Adolphus College",
    "University Of Evansville",
    "Rockhurst University",
    "University Of Tulsa",
    "Wofford College",
    "Florida Institute Of Technology",
    "Southern Methodist University",
    "Rollins College",
    "Allegheny College",
    "Northeastern University",
    "Loras College",
    "Whitman College",
    "Bentley University",
    "Taylor University",
    "Lake Forest College",
    "Westmont College",
    "Sewanee The University Of The South",
    "Wartburg College",
    "Berry College",
    "Drake University",
    "Seattle University",
    "The New School College Performing Arts",
    "University Of Denver",
    "Fairfield University",
    "Misericordia University",
    "Southwestern University",
    "Yeshiva University",
    "Hope College",
    "Hollins University",
    "Clarkson University",
    "Saint Josephs University",
    "John Carroll University",
    "Boston University",
    "Ursinus College",
    "Cornell College",
    "Clark University",
    "Marquette University",
    "Hobart And William Smith Colleges",
    "Nichols College",
    "Whitworth University",
    "Agnes Scott College",
    "Saint Louis University",
    "Dakota Wesleyan University",
    "Fordham University",
    "Norwich University",
    "Creighton University",
    "Northwest Nazarene University",
    "Goshen College",
    "Gonzaga University",
    "University Of Dallas",
    "Loyola Marymount University",
    "Samford University",
    "Providence College",
    "Illinois Wesleyan University",
    "University Of Scranton",
    "Rensselaer Polytechnic Institute",
    "Duquesne University",
    "Milwaukee School Of Engineering",
    "Villanova University",
    "Ohio Wesleyan University",
    "Santa Clara University",
    "Marist College",
    "Loyola University New Orleans",
    "Rose Hulman Institute Of Technology",
    "Union University",
    "Stevens Institute Of Technology",
    "Nebraska Wesleyan University",
    "Union College",
    "Ohio Northern University",
    "Loyola University Chicago",
    "Point Loma Nazarene University",
    "Merrimack College",
    "Harding University",
    "Bradley University",
    "Augustana University",
    "University Of Puget Sound",
    "American University",
    "Bob Jones University",
    "Chapman University",
    "Illinois Institute Of Technology",
    "Pepperdine University",
    "University Of San Diego",
    "Suffolk University",
    "Albany College Of Pharmacy And Health Sciences",
    "Endicott College",
    "Liberty University",
    "New York University",
    "University Of The Sciences",
    "Biola University",
    "Berklee College Of Music",
    "University Of The Pacific",
    "Wentworth Institute Of Technology",
    "Butler University",
    "University Of Portland",
    "Seattle Pacific University",
    "Emerson College",
    "Rhode Island School Of Design",
    "Mcphs University",
    "Brigham Young University",
    "Dunwoody College Of Technology",
    "Menlo College",
    "(In-state)University Of California Santa Barbara",
    "(In-state)Florida State University",
    "(In-state)University Of Oklahoma",
    "(In-state)University Of North Carolina At Chapel Hill",
    "(In-state)University Of Virginia",
    "(In-state)University Of Michigan",
    "(In-state)James Madison University",
    "(In-state)California State University Long Beach",
    "(In-state)Virginia Military Institute",
    "(In-state)University Of Kansas",
    "(In-state)Purdue University",
    "(In-state)University Of Idaho",
    "(In-state)University Of Colorado At Boulder",
    "(In-state)University Of Wisconsin Madison",
    "(In-state)College Of William And Mary",
    "(In-state)University Of North Dakota",
    "(In-state)Suny College Of Environmental Science And Forestry",
    "(In-state)University Of California Los Angeles",
    "(In-state)North Dakota State University",
    "(In-state)University Of California Berkeley",
    "(In-state)Penn State University Park",
    "(In-state)University Of Massachusetts Lowell",
    "(In-state)University Of California Santa Cruz",
    "(In-state)University Of California Davis",
    "(In-state)Indiana University Bloomington",
    "(In-state)University Of Minnesota Crookston",
    "(In-state)University Of Minnesota Twin Cities",
    "(In-state)University Of Massachusetts Boston",
    "(In-state)Georgia Institute Of Technology",
    "(In-state)Arizona State University",
    "(In-state)Michigan Technological University",
    "(In-state)Colorado School Of Mines",
    "(In-state)University Of Georgia",
    "(In-state)University Of California Irvine",
    "(In-state)San Diego State University",
    "(In-state)University Of Alabama",
    "(In-state)Texas Tech University",
    "(In-state)Penn State Worthington Scranton",
    "(In-state)Iowa State University",
    "(In-state)University Of Florida",
    "(In-state)University Of Wisconsin La Crosse",
    "(In-state)Kansas State University",
    "(In-state)Louisiana Tech University",
    "(In-state)University Of Louisville",
    "(In-state)Christopher Newport University",
    "(In-state)University Of California Riverside",
    "(In-state)University Of New Hampshire",
    "(In-state)University Of Washington",
    "(In-state)University Of Vermont",
    "(In-state)Texas Am University",
    "(In-state)University Of Kentucky",
    "(In-state)University Of Texas At Austin",
    "(In-state)University Of Northern Iowa",
    "(In-state)Colorado State University",
    "(In-state)University Of Central Florida",
    "(In-state)Texas State University",
    "(In-state)University Of Texas At Dallas",
    "(In-state)University Of Wyoming",
    "(In-state)College Of Charleston",
    "(In-state)University Of Mississippi",
    "(In-state)University Of North Carolina At Charlotte",
    "(In-state)California State University Fullerton",
    "(In-state)University Of Missouri Kansas City",
    "(In-state)University Of Maryland College Park",
    "(In-state)University Of Arizona",
    "(In-state)University Of Houston Downtown",
    "(In-state)University Of Nebraska Lincoln",
    "(In-state)University Of Houston",
    "(In-state)University Of Utah",
    "(In-state)Florida International University",
    "(In-state)Appalachian State University",
    "(In-state)University Of Connecticut",
    "(In-state)Maine Maritime Academy",
    "(In-state)University Of South Florida",
    "(In-state)University Of Massachusetts Amherst",
    "(In-state)University Of Iowa",
    "(In-state)Oregon State University",
    "(In-state)University Of Maryland Baltimore County",
    "(In-state)Washington State University",
    "(In-state)Oakland University",
    "(In-state)Michigan State University",
    "(In-state)Utah State University",
    "(In-state)Oklahoma State University",
    "(In-state)The College Of New Jersey",
    "(In-state)University Of Illinois At Urbana Champaign",
    "(In-state)West Virginia University",
    "(In-state)Ohio University",
    "(In-state)University Of Delaware",
    "(In-state)Auburn University",
    "(In-state)University Of Pittsburgh",
    "(In-state)University Of Cincinnati",
    "(In-state)California Polytechnic State University San Luis Obispo",
    "(In-state)University Of North Florida",
    "(In-state)University Of Oregon",
    "(In-state)Virginia Commonwealth University",
    "(In-state)Temple University",
    "(In-state)George Mason University",
    "(In-state)University Of Colorado At Denver",
    "(Out-of-state)University Of California Santa Barbara",
    "(Out-of-state)Florida State University",
    "(Out-of-state)University Of Oklahoma",
    "(Out-of-state)University Of North Carolina At Chapel Hill",
    "(Out-of-state)University Of Virginia",
    "(Out-of-state)University Of Michigan",
    "(Out-of-state)James Madison University",
    "(Out-of-state)California State University Long Beach",
    "(Out-of-state)Virginia Military Institute",
    "(Out-of-state)University Of Kansas",
    "(Out-of-state)Purdue University",
    "(Out-of-state)University Of Idaho",
    "(Out-of-state)University Of Colorado At Boulder",
    "(Out-of-state)University Of Wisconsin Madison",
    "(Out-of-state)College Of William And Mary",
    "(Out-of-state)University Of North Dakota",
    "(Out-of-state)Suny College Of Environmental Science And Forestry",
    "(Out-of-state)University Of California Los Angeles",
    "(Out-of-state)North Dakota State University",
    "(Out-of-state)University Of California Berkeley",
    "(Out-of-state)Penn State University Park",
    "(Out-of-state)University Of Massachusetts Lowell",
    "(Out-of-state)University Of California Santa Cruz",
    "(Out-of-state)University Of California Davis",
    "(Out-of-state)Indiana University Bloomington",
    "(Out-of-state)University Of Minnesota Crookston",
    "(Out-of-state)University Of Minnesota Twin Cities",
    "(Out-of-state)University Of Massachusetts Boston",
    "(Out-of-state)Georgia Institute Of Technology",
    "(Out-of-state)Arizona State University",
    "(Out-of-state)Michigan Technological University",
    "(Out-of-state)Colorado School Of Mines",
    "(Out-of-state)University Of Georgia",
    "(Out-of-state)University Of California Irvine",
    "(Out-of-state)San Diego State University",
    "(Out-of-state)University Of Alabama",
    "(Out-of-state)Texas Tech University",
    "(Out-of-state)Penn State Worthington Scranton",
    "(Out-of-state)Iowa State University",
    "(Out-of-state)University Of Florida",
    "(Out-of-state)University Of Wisconsin La Crosse",
    "(Out-of-state)Kansas State University",
    "(Out-of-state)Louisiana Tech University",
    "(Out-of-state)University Of Louisville",
    "(Out-of-state)Christopher Newport University",
    "(Out-of-state)University Of California Riverside",
    "(Out-of-state)University Of New Hampshire",
    "(Out-of-state)University Of Washington",
    "(Out-of-state)University Of Vermont",
    "(Out-of-state)Texas Am University",
    "(Out-of-state)University Of Kentucky",
    "(Out-of-state)University Of Texas At Austin",
    "(Out-of-state)University Of Northern Iowa",
    "(Out-of-state)Colorado State University",
    "(Out-of-state)University Of Central Florida",
    "(Out-of-state)Texas State University",
    "(Out-of-state)University Of Texas At Dallas",
    "(Out-of-state)University Of Wyoming",
    "(Out-of-state)College Of Charleston",
    "(Out-of-state)University Of Mississippi",
    "(Out-of-state)University Of North Carolina At Charlotte",
    "(Out-of-state)California State University Fullerton",
    "(Out-of-state)University Of Missouri Kansas City",
    "(Out-of-state)University Of Maryland College Park",
    "(Out-of-state)University Of Arizona",
    "(Out-of-state)University Of Houston Downtown",
    "(Out-of-state)University Of Nebraska Lincoln",
    "(Out-of-state)University Of Houston",
    "(Out-of-state)University Of Utah",
    "(Out-of-state)Florida International University",
    "(Out-of-state)Appalachian State University",
    "(Out-of-state)University Of Connecticut",
    "(Out-of-state)Maine Maritime Academy",
    "(Out-of-state)University Of South Florida",
    "(Out-of-state)University Of Massachusetts Amherst",
    "(Out-of-state)University Of Iowa",
    "(Out-of-state)Oregon State University",
    "(Out-of-state)University Of Maryland Baltimore County",
    "(Out-of-state)Washington State University",
    "(Out-of-state)Oakland University",
    "(Out-of-state)Michigan State University",
    "(Out-of-state)Utah State University",
    "(Out-of-state)Oklahoma State University",
    "(Out-of-state)The College Of New Jersey",
    "(Out-of-state)University Of Illinois At Urbana Champaign",
    "(Out-of-state)West Virginia University",
    "(Out-of-state)Ohio University",
    "(Out-of-state)University Of Delaware",
    "(Out-of-state)Auburn University",
    "(Out-of-state)University Of Pittsburgh",
    "(Out-of-state)University Of Cincinnati",
    "(Out-of-state)California Polytechnic State University San Luis Obispo",
    "(Out-of-state)University Of North Florida",
    "(Out-of-state)University Of Oregon",
    "(Out-of-state)Virginia Commonwealth University",
    "(Out-of-state)Temple University",
    "(Out-of-state)George Mason University",
    "(Out-of-state)University Of Colorado At Denver"
]

const collegeFullCost = {
    "Hamilton College" : 75370,
    "Bates College" : 75680,
    "Wesleyan University" : 78735,
    "Princeton University" : 63294,
    "Colorado College" : 78080,
    "University Of Pennsylvania" : 76826,
    "Cornell University" : 78002,
    "Harvard College" : 75891,
    "Washington And Lee University" : 77600,
    "Yale University" : 79320,
    "Williams College" : 66540,
    "Swarthmore College" : 74090,
    "Grinnell College" : 73244,
    "Carleton College" : 77100,
    "Brown University" : 80348,
    "Smith College" : 77698,
    "Haverford College" : 78628,
    "Columbia University" : 80809,
    "Reed College" : 78350,
    "Washington University In St Louis" : 79586,
    "Mount Holyoke College" : 76138,
    "Middlebury College" : 76946,
    "Dartmouth College" : 80784,
    "Connecticut College" : 77315,
    "Bowdoin College" : 69960,
    "Boston College" : 78672,
    "Amherst College" : 79600,
    "Skidmore College" : 76670,
    "Wellesley College" : 77020,
    "Vanderbilt University" : 76144,
    "Northwestern University" : 81228,
    "Colgate University" : 77575,
    "Oberlin College" : 77796,
    "Bryn Mawr College" : 76780,
    "Emory University" : 73214,
    "Occidental College" : 76016,
    "Johns Hopkins University" : 77348,
    "Colby College" : 76925,
    "University Of Chicago" : 81531,
    "Harvey Mudd College" : 79789,
    "Pomona College" : 75694,
    "Davidson College" : 70285,
    "California Institute Of Technology" : 77718,
    "St Olaf College" : 65410,
    "Duke University" : 80470,
    "Brandeis University" : 76195,
    "University Of Notre Dame" : 76683,
    "College Of The Holy Cross" : 73980,
    "Georgetown University" : 80458,
    "Wake Forest University" : 74655,
    "Pitzer College" : 75360,
    "University Of Rochester" : 78028,
    "Scripps College" : 79996,
    "Stanford University" : 78218,
    "University Of Dayton" : 63220,
    "Loyola University Maryland" : 70655,
    "Dickinson College" : 74779,
    "University Of Southern California" : 76188,
    "Babson College" : 75694,
    "Case Western Reserve University" : 72736,
    "Wabash College" : 60200,
    "Lehigh University" : 72065,
    "Rochester Institute Of Technology" : 67270,
    "Lafayette College" : 74926,
    "University Of Miami" : 73712,
    "Macalester College" : 74271,
    "Rice University" : 69807,
    "Cooper Union For The Advancement Of Science And Art" : 64305,
    "Rhodes College" : 66470,
    "Stonehill College" : 65762,
    "Lawrence University" : 64260,
    "Valparaiso University" : 58726,
    "College Of Wooster" : 69300,
    "College Of The Ozarks" : 30662,
    "Bryant University" : 66017,
    "Worcester Polytechnic Institute" : 71706,
    "Cedarville University" : 44276,
    "Spelman College" : 54740,
    "Syracuse University" : 75652,
    "Hendrix College" : 66310,
    "Luther College" : 59775,
    "Mercer University" : 54856,
    "George Washington University" : 77351,
    "Gustavus Adolphus College" : 61040,
    "University Of Evansville" : 55216,
    "Rockhurst University" : 55805,
    "University Of Tulsa" : 64217,
    "Wofford College" : 65183,
    "Florida Institute Of Technology" : 61226,
    "Southern Methodist University" : 79050,
    "Rollins College" : 72756,
    "Allegheny College" : 67560,
    "Northeastern University" : 75662,
    "Loras College" : 46929,
    "Whitman College" : 71968,
    "Bentley University" : 73985,
    "Taylor University" : 48755,
    "Lake Forest College" : 64560,
    "Westmont College" : 66220,
    "Sewanee The University Of The South" : 64630,
    "Wartburg College" : 57672,
    "Berry College" : 54540,
    "Drake University" : 60318,
    "Seattle University" : 65970,
    "The New School College Performing Arts" : 71636,
    "University Of Denver" : 71929,
    "Fairfield University" : 69815,
    "Misericordia University" : 52710,
    "Southwestern University" : 59780,
    "Yeshiva University" : 67150,
    "Hope College" : 50310,
    "Hollins University" : 57410,
    "Clarkson University" : 72270,
    "Saint Josephs University" : 65060,
    "John Carroll University" : 61715,
    "Boston University" : 77662,
    "Ursinus College" : 72062,
    "Cornell College" : 60448,
    "Clark University" : 60152,
    "Marquette University" : 62438,
    "Hobart And William Smith Colleges" : 76645,
    "Nichols College" : 54090,
    "Whitworth University" : 62890,
    "Agnes Scott College" : 58300,
    "Saint Louis University" : 65092,
    "Dakota Wesleyan University" : 41560,
    "Fordham University" : 78844,
    "Norwich University" : 61054,
    "Creighton University" : 58618,
    "Northwest Nazarene University" : 45390,
    "Goshen College" : 49670,
    "Gonzaga University" : 64802,
    "University Of Dallas" : 62050,
    "Loyola Marymount University" : 72475,
    "Samford University" : 51314,
    "Providence College" : 72380,
    "Illinois Wesleyan University" : 65676,
    "University Of Scranton" : 65902,
    "Duquesne University" : 59104,
    "Milwaukee School Of Engineering" : 57256,
    "Villanova University" : 73274,
    "Ohio Wesleyan University" : 63166,
    "Santa Clara University" : 75615,
    "Marist College" : 65035,
    "Loyola University New Orleans" : 60148,
    "Rose Hulman Institute Of Technology" : 71682,
    "Union University" : 56500,
    "Stevens Institute Of Technology" : 74516,
    "Union College" : 37900,
    "Ohio Northern University" : 50790,
    "Loyola University Chicago" : 64268,
    "Point Loma Nazarene University" : 53214,
    "Merrimack College" : 62932,
    "Harding University" : 32984,
    "Bradley University" : 50200,
    "Augustana University" : 50238,
    "University Of Puget Sound" : 70686,
    "American University" : 68024,
    "Bob Jones University" : 33050,
    "Chapman University" : 78272,
    "Illinois Institute Of Technology" : 71286,
    "Pepperdine University" : 77912,
    "University Of San Diego" : 72033,
    "Suffolk University" : 63765,
    "Endicott College" : 51450,
    "Liberty University" : 43486,
    "New York University" : 78744,
    "University Of The Sciences" : 48925,
    "Biola University" : 70690,
    "Berklee College Of Music" : 69300,
    "University Of The Pacific" : 68962,
    "Wentworth Institute Of Technology" : 54410,
    "University Of Portland" : 67274,
    "Seattle Pacific University" : 64575,
    "Emerson College" : 73766,
    "Rhode Island School Of Design" : 75520,
    "Mcphs University" : 57048,
    "Brigham Young University" : 19416,
    "Dunwoody College Of Technology" : 30698,
    "Menlo College" : 64663,
    "(In-state)University Of California Santa Barbara" : 36508,
    "(In-state)Florida State University" : 23987,
    "(In-state)University Of Oklahoma" : 30374,
    "(In-state)University Of North Carolina At Chapel Hill" : 24552,
    "(In-state)University Of Virginia" : 35744,
    "(In-state)University Of Michigan" : 31484,
    "(In-state)James Madison University" : 28640,
    "(In-state)California State University Long Beach" : 25258,
    "(In-state)Virginia Military Institute" : 32370,
    "(In-state)University Of Kansas" : 25476,
    "(In-state)Purdue University" : 21182,
    "(In-state)University Of Idaho" : 21820,
    "(In-state)University Of Colorado At Boulder" : 31442,
    "(In-state)University Of Wisconsin Madison" : 27272,
    "(In-state)College Of William And Mary" : 40034,
    "(In-state)University Of North Dakota" : 24652,
    "(In-state)Suny College Of Environmental Science And Forestry" : 27635,
    "(In-state)University Of California Los Angeles" : 33166,
    "(In-state)North Dakota State University" : 19711,
    "(In-state)University Of California Berkeley" : 36896,
    "(In-state)Penn State University Park" : 36200,
    "(In-state)University Of Massachusetts Lowell" : 31984,
    "(In-state)University Of California Santa Cruz" : 37817,
    "(In-state)University Of California Davis" : 35444,
    "(In-state)Indiana University Bloomington" : 24417,
    "(In-state)University Of Minnesota Crookston" : 24074,
    "(In-state)University Of Minnesota Twin Cities" : 29237,
    "(In-state)Georgia Institute Of Technology" : 25572,
    "(In-state)Arizona State University" : 29449,
    "(In-state)Michigan Technological University" : 31349,
    "(In-state)Colorado School Of Mines" : 37199,
    "(In-state)University Of Georgia" : 26084,
    "(In-state)University Of California Irvine" : 33959,
    "(In-state)San Diego State University" : 30240,
    "(In-state)University Of Alabama" : 28212,
    "(In-state)Texas Tech University" : 27156,
    "(In-state)Penn State Worthington Scranton" : 16824,
    "(In-state)Iowa State University" : 21900,
    "(In-state)University Of Florida" : 21431,
    "(In-state)University Of Wisconsin La Crosse" : 17837,
    "(In-state)Kansas State University" : 25323,
    "(In-state)Louisiana Tech University" : 19887,
    "(In-state)University Of Louisville" : 29678,
    "(In-state)Christopher Newport University" : 31738,
    "(In-state)University Of California Riverside" : 34247,
    "(In-state)University Of New Hampshire" : 34830,
    "(In-state)University Of Washington" : 29612,
    "(In-state)University Of Vermont" : 36374,
    "(In-state)Texas Am University" : 30638,
    "(In-state)University Of Kentucky" : 31430,
    "(In-state)University Of Texas At Austin" : 28202,
    "(In-state)University Of Northern Iowa" : 21294,
    "(In-state)Colorado State University" : 28607,
    "(In-state)University Of Central Florida" : 22298,
    "(In-state)Texas State University" : 27086,
    "(In-state)University Of Texas At Dallas" : 30744,
    "(In-state)University Of Wyoming" : 20790,
    "(In-state)College Of Charleston" : 18054,
    "(In-state)University Of Mississippi" : 25642,
    "(In-state)University Of North Carolina At Charlotte" : 24723,
    "(In-state)California State University Fullerton" : 28275,
    "(In-state)University Of Missouri Kansas City" : 26248,
    "(In-state)University Of Maryland College Park" : 27857,
    "(In-state)University Of Arizona" : 30366,
    "(In-state)University Of Houston Downtown" : 9932,
    "(In-state)University Of Nebraska Lincoln" : 25219,
    "(In-state)University Of Houston" : 26743,
    "(In-state)University Of Utah" : 25213,
    "(In-state)Florida International University" : 23376,
    "(In-state)Appalachian State University" : 19922,
    "(In-state)University Of Connecticut" : 35074,
    "(In-state)Maine Maritime Academy" : 27378,
    "(In-state)University Of South Florida" : 23446,
    "(In-state)University Of Massachusetts Amherst" : 32271,
    "(In-state)University Of Iowa" : 25296,
    "(In-state)Oregon State University" : 30131,
    "(In-state)University Of Maryland Baltimore County" : 28328,
    "(In-state)Washington State University" : 28520,
    "(In-state)Oakland University" : 27534,
    "(In-state)Michigan State University" : 29156,
    "(In-state)Utah State University" : 18740,
    "(In-state)Oklahoma State University" : 23558,
    "(In-state)The College Of New Jersey" : 36183,
    "(In-state)University Of Illinois At Urbana Champaign" : 31354,
    "(In-state)West Virginia University" : 23738,
    "(In-state)Ohio University" : 28912,
    "(In-state)Auburn University" : 32678,
    "(In-state)University Of Pittsburgh" : 34369,
    "(In-state)California Polytechnic State University San Luis Obispo" : 30544,
    "(In-state)University Of North Florida" : 21615,
    "(In-state)University Of Oregon" : 30312,
    "(In-state)Virginia Commonwealth University" : 30919,
    "(In-state)Temple University" : 33490,
    "(In-state)George Mason University" : 29878,
    "(In-state)University Of Colorado At Denver" : 24524,
    "(Out-of-state)University Of California Santa Barbara" : 66262,
    "(Out-of-state)Florida State University" : 39153,
    "(Out-of-state)University Of Oklahoma" : 45755,
    "(Out-of-state)University Of North Carolina At Chapel Hill" : 51731,
    "(Out-of-state)University Of Virginia" : 69039,
    "(Out-of-state)University Of Michigan" : 67802,
    "(Out-of-state)James Madison University" : 45540,
    "(Out-of-state)California State University Long Beach" : 37138,
    "(Out-of-state)Virginia Military Institute" : 60380,
    "(Out-of-state)University Of Kansas" : 42344,
    "(Out-of-state)Purdue University" : 39984,
    "(Out-of-state)University Of Idaho" : 41056,
    "(Out-of-state)University Of Colorado At Boulder" : 57260,
    "(Out-of-state)University Of Wisconsin Madison" : 55160,
    "(Out-of-state)College Of William And Mary" : 62689,
    "(Out-of-state)University Of North Dakota" : 28922,
    "(Out-of-state)Suny College Of Environmental Science And Forestry" : 37545,
    "(Out-of-state)University Of California Los Angeles" : 62920,
    "(Out-of-state)North Dakota State University" : 24014,
    "(Out-of-state)University Of California Berkeley" : 66650,
    "(Out-of-state)Penn State University Park" : 36200,
    "(Out-of-state)University Of Massachusetts Lowell" : 49910,
    "(Out-of-state)University Of California Santa Cruz" : 69011,
    "(Out-of-state)University Of California Davis" : 64070,
    "(Out-of-state)Indiana University Bloomington" : 49982,
    "(Out-of-state)University Of Minnesota Crookston" : 24074,
    "(Out-of-state)University Of Minnesota Twin Cities" : 47535,
    "(Out-of-state)Georgia Institute Of Technology" : 46684,
    "(Out-of-state)Arizona State University" : 47539,
    "(Out-of-state)Michigan Technological University" : 51651,
    "(Out-of-state)Colorado School Of Mines" : 57899,
    "(Out-of-state)University Of Georgia" : 45124,
    "(Out-of-state)University Of California Irvine" : 63713,
    "(Out-of-state)San Diego State University" : 42120,
    "(Out-of-state)University Of Alabama" : 47682,
    "(Out-of-state)Texas Tech University" : 39426,
    "(Out-of-state)Penn State Worthington Scranton" : 25814,
    "(Out-of-state)Iowa State University" : 37088,
    "(Out-of-state)University Of Florida" : 43708,
    "(Out-of-state)University Of Wisconsin La Crosse" : 26656,
    "(Out-of-state)Kansas State University" : 40467,
    "(Out-of-state)Louisiana Tech University" : 31021,
    "(Out-of-state)University Of Louisville" : 46024,
    "(Out-of-state)Christopher Newport University" : 44204,
    "(Out-of-state)University Of California Riverside" : 64001,
    "(Out-of-state)University Of New Hampshire" : 52170,
    "(Out-of-state)University Of Washington" : 56981,
    "(Out-of-state)University Of Vermont" : 61262,
    "(Out-of-state)Texas Am University" : 57260,
    "(Out-of-state)University Of Kentucky" : 50240,
    "(Out-of-state)University Of Texas At Austin" : 55704,
    "(Out-of-state)University Of Northern Iowa" : 31836,
    "(Out-of-state)Colorado State University" : 47327,
    "(Out-of-state)University Of Central Florida" : 38397,
    "(Out-of-state)Texas State University" : 39356,
    "(Out-of-state)University Of Texas At Dallas" : 55722,
    "(Out-of-state)University Of Wyoming" : 34530,
    "(Out-of-state)College Of Charleston" : 38384,
    "(Out-of-state)University Of Mississippi" : 41914,
    "(Out-of-state)University Of North Carolina At Charlotte" : 38157,
    "(Out-of-state)California State University Fullerton" : 40155,
    "(Out-of-state)University Of Missouri Kansas City" : 42349,
    "(Out-of-state)University Of Maryland College Park" : 54491,
    "(Out-of-state)University Of Arizona" : 54393,
    "(Out-of-state)University Of Houston Downtown" : 22292,
    "(Out-of-state)University Of Nebraska Lincoln" : 42349,
    "(Out-of-state)University Of Houston" : 42013,
    "(Out-of-state)University Of Utah" : 45847,
    "(Out-of-state)Florida International University" : 35774,
    "(Out-of-state)Appalachian State University" : 34729,
    "(Out-of-state)University Of Connecticut" : 57742,
    "(Out-of-state)Maine Maritime Academy" : 41758,
    "(Out-of-state)University Of South Florida" : 34360,
    "(Out-of-state)University Of Massachusetts Amherst" : 52259,
    "(Out-of-state)University Of Iowa" : 47259,
    "(Out-of-state)Oregon State University" : 50321,
    "(Out-of-state)University Of Maryland Baltimore County" : 43962,
    "(Out-of-state)Washington State University" : 43463,
    "(Out-of-state)Oakland University" : 37944,
    "(Out-of-state)Michigan State University" : 54462,
    "(Out-of-state)Utah State University" : 33685,
    "(Out-of-state)Oklahoma State University" : 39078,
    "(Out-of-state)The College Of New Jersey" : 48071,
    "(Out-of-state)University Of Illinois At Urbana Champaign" : 48804,
    "(Out-of-state)West Virginia University" : 40082,
    "(Out-of-state)Ohio University" : 38706,
    "(Out-of-state)Auburn University" : 52838,
    "(Out-of-state)University Of Pittsburgh" : 48397,
    "(Out-of-state)California Polytechnic State University San Luis Obispo" : 42424,
    "(Out-of-state)University Of North Florida" : 35333,
    "(Out-of-state)University Of Oregon" : 55764,
    "(Out-of-state)Virginia Commonwealth University" : 51567,
    "(Out-of-state)Temple University" : 47790,
    "(Out-of-state)George Mason University" : 53338,
    "(Out-of-state)University Of Colorado At Denver" : 45134
}



const select = document.querySelector("#brow");
const select1 = document.querySelector("#brow1");
for (let element of collegeNames) {
    const newh1 = document.createElement('option');
    newh1.setAttribute('value', element);
    select.appendChild(newh1);
}

for (let element of collegeNames) {
    const newh1 = document.createElement('option');
    newh1.setAttribute('value', element);
    select1.appendChild(newh1);
}

document.addEventListener('click', function(event) {
    if(event.target.matches('.delImg')) {
        const rent = event.target.parentElement.parentElement
        rent.remove()
    }
    if(event.target.matches(".solvPlusImg")) {
        const solvContain = event.target.parentElement.parentElement.parentElement.parentElement
        const solvDiv = document.createElement('div')
        solvDiv.className="rangeContain"
        solvContain.appendChild(solvDiv);
        const solvLabel = document.createElement('input');
        solvLabel.classList.add('form-label', 'rangeLabel');
        solvLabel.placeholder = "Parents, Aid, Etc."
        solvDiv.appendChild(solvLabel);
        const solvAssist = document.createElement('input');
        solvAssist.type="number";
        solvAssist.className="rangeAssist";
        solvAssist.placeholder = "Amt. Per Year"
        solvDiv.appendChild(solvAssist);
        const solvRange = document.createElement('input');
        solvRange.type = "range";

        solvRange.className = 'form-range';
        solvRange.className+=' range';
        solvRange.min = '0';
        solvRange.max = '99500';
        solvRange.value = '0';
        solvRange.step = '500';
        solvDiv.appendChild(solvRange);
        const delBtn = document.createElement('button');
        delBtn.className = "solvDelBtn";
        solvDiv.appendChild(delBtn);
        const delImg = document.createElement('img')
        delImg.src = "../images/delete_black_24dp.svg"
        delImg.className = "delImg"
        delBtn.appendChild(delImg)
    }
})

// const fullcosts = document.querySelectorAll(".fullcost");
const years = 4;

document.addEventListener('input', function(event) {
    if(event.target.matches('.range')) {
        event.target.previousElementSibling.value = event.target.value;
        const school = event.target.parentElement.parentElement.parentElement
        const debt = school.querySelector(".fullcost").value;
        let full = school.querySelector(".fullcost").value;
        const subtractors = school.querySelectorAll(".range");
        subtractors.forEach(subtractor => full -= subtractor.value);
        school.querySelector(".display-5").innerHTML = '$'+(full*years).toLocaleString('en-US');
        const boxes = school.querySelectorAll(".flexbox-item-1")
        for(let box of boxes) {
            box.style.height = (full/debt)*100+'%';
        }}
    if(event.target.matches('.fullcost')) {
        const school = event.target.parentElement.parentElement.parentElement.parentElement
        const subtractors = school.querySelectorAll(".range");
        const debt = school.querySelector(".fullcost").value
        let full = chool.querySelector(".fullcost").value
        for(let range of subtractors) {
            full -= range.value
        }
        school.querySelector(".display-5").innerHTML = '$' + (full*years).toLocaleString('en-US');
        const boxes = school.querySelectorAll(".flexbox-item-1");
        for(let box of boxes) {
            const height = full/debt * 100;
            box.style.height = height +'%';
        }}
    if(event.target.matches('.rangeAssist')) {
        const school = event.target.parentElement.parentElement.parentElement
        event.target.nextElementSibling.value = event.target.value;
        const subtractors = school.querySelectorAll(".range");
        const debt = school.querySelector(".fullcost").value
        let full = school.querySelector(".fullcost").value
        for(let range of subtractors) {
            full -= range.value
        }
        school.querySelector(".display-5").innerHTML = '$' + (full*years).toLocaleString('en-US');
        const boxes = school.querySelectorAll(".flexbox-item-1");
        for(let box of boxes) {
            const height = full/debt * 100;
            box.style.height = height +'%';
        }}
    if(event.target.matches('.schoolInput')) {
        const school = event.target.parentElement.parentElement.parentElement
        const name = school.querySelector(".schoolInput").value;
        school.querySelector('.fullcost').value = collegeFullCost[name];
        const subtractors = school.querySelectorAll(".range");
        const debt = school.querySelector(".fullcost").value
        let full = school.querySelector(".fullcost").value
        for(let range of subtractors) {
            full -= range.value
        }
        school.querySelector(".display-5").innerHTML = '$' + (full*years).toLocaleString('en-US');
        const boxes = school.querySelectorAll(".flexbox-item-1");
        for(let box of boxes) {
            const height = full/debt * 100;
            box.style.height = height +'%';
        }}
})